spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud/products?ssl={"rejectUnauthorized":true}
    username: 6flx0m0mb2indc93hygn
    password: pscale_pw_oExFN4jWbSIyuyat6X7l0h1CvDpVZwxqI3czBYUstEd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: products
      database-platform: org.hibernate.dialect.MYSQLDialect
